<?php
declare(strict_types=1);

require_once (__DIR__ . '/../../../vendor/autoload.php');
require_once (__DIR__ . '/../../../src/04_practices/Constant.php');

use exp\src\practice\MonicaStudio;
use PHPUnit\Framework\TestCase;

class MonicaStudioTest extends TestCase {
    private $monica_studio;
    public function setUp(): void
    {
        $this->monica_studio = new MonicaStudio();
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function getSaleGamesData(): array {
        return [
            [
                WINTER_SEASON,
                [
                'Game X in MonicaStudio',
                'Game Y in MonicaStudio'
                ]
            ],
            [SPRING_SEASON, []],
            [SUMMER_SEASON, []],
            [FALL_SEASON, []]
        ];
    }

    /**
     * @return void
     * @dataProvider getSaleGamesData
     */
    public function testGetSaleGamesReturnCorrectData(int $season, array $result) {
        $actual_result = $this->monica_studio->getSaleGames($season);

        $this->assertSame($result, $actual_result);
    }

    public function testGetStudioName() {
        $this->assertEquals('Santa Monica Studio', $this->monica_studio->getStudioName());
    }
}

// DONE
